### ISSUE TITLE
Crash on Xcode 8

### ISSUE THREAD

**Issue by matkuznik** [antitypical/Result#168]
When I try to run application on Xcode 8 (8.0 beta (8S128d)) I have this error:

```
dyld: Symbol not found: __TMps9ErrorType
  Referenced from: {home_path}/Library/Developer/CoreSimulator/Devices/1DE73ABE-4DD2-482E-BF82-F36D99A47D51/data/Containers/Bundle/Application/148926DF-27FD-40B9-AE3D-597ACEEB4506/StartTimeTest.app/Frameworks/Result.framework/Result
  Expected in: {home_path}/Library/Developer/CoreSimulator/Devices/1DE73ABE-4DD2-482E-BF82-F36D99A47D51/data/Containers/Bundle/Application/148926DF-27FD-40B9-AE3D-597ACEEB4506/StartTimeTest.app/Frameworks/libswiftCore.dylib
 in {home_path}/Library/Developer/CoreSimulator/Devices/1DE73ABE-4DD2-482E-BF82-F36D99A47D51/data/Containers/Bundle/Application/148926DF-27FD-40B9-AE3D-597ACEEB4506/StartTimeTest.app/Frameworks/Result.framework/Result
```

To reproduce just create an empty project. Add podfile with content:

```
platform :ios, :deployment_target => '8.0'
inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'TargetName' do
    pod 'Result', '~> 2.1'
end
```

install pods and run.
Thanks.

**Comment by mdiep** [comment]
I believe that Xcode 8 is trying to compile Result with Swift 3, and Result isn't yet compatible with Swift 3. (See #166 and #167).

If you specify 2.1.1, then Xcode should try to build with Swift 2.3.

**Comment by matkuznik** [comment]
sorry, I forgot to mention, project is converted to swift 2.3. The Result version is 2.1.1

```
 pod install
Analysing dependencies
Downloading dependencies
Using Result (2.1.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed. 
```

**Comment by mdiep** [comment]
Have you tried doing a clean build?

This isn't really a Result bug. It's an issue with your build, stale products, build settings, or Xcode.

**Comment by matkuznik** [comment]
What you mean by a clean build? What I did:
 1. create an empty project,
 2. add podfile by `pod init` (with content as above)
 3. `pod install`
 4. migrate to 2.3 
 5. run

Also tried on other Mac and it was the same.

**Comment by matkuznik** [comment]
Ok. This is an issue (?) in Xcode. What I did wrong is was converting to swift 2.3 only the Result.framework (selected by default). After select all listed items (Pods_xxx.framework etc) there is no errors.
